### ISSUE TITLE
Handling user renames

### ISSUE THREAD

**Issue by danmichaelo** [danmichaelo/UKBot#12]
If a participating user is renamed during the contest, it can cause a crash.

Say that a user is renamed from A to B in the middle of a contest. Revisions made by the user are stored with `user=A` in the `contribs` table. After the rename, `add_contribs_from_db()` will only load contributions for `user=B` and `add_contribs_from_wiki()` will then find the same revisions and try to insert them for that user. This raises an IntegrityError, since the (revision_id, site_id) is already present in that table for `user=A`:

```
Traceback (most recent call last):
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ENV/bin/ukbot", line 11, in <module>
    load_entry_point('ukbot', 'console_scripts', 'ukbot')()
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ukbot/ukbot.py", line 2714, in main
    contest.run(args.simulate, args.output)
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ukbot/ukbot.py", line 2051, in run
    user.save_contribs_to_db(self.sql)
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ukbot/ukbot.py", line 759, in save_contribs_to_db
    """, contribs_query_params
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ENV/lib/python3.4/site-packages/mysql/connector/cursor.py", line 662, in executemany
    return self.execute(stmt)
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ENV/lib/python3.4/site-packages/mysql/connector/cursor.py", line 559, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ENV/lib/python3.4/site-packages/mysql/connector/connection.py", line 494, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/mnt/nfs/labstore-secondary-tools-project/ukbot/ENV/lib/python3.4/site-packages/mysql/connector/connection.py", line 396, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry '17852381-fi.wikipedia.org' for key 'PRIMARY'
```

Simple solution would be to extend the primary key to also include user. A more proper fix would be to update the existing rows.

**Comment by zache-fi** [comment]
@danmichaelo , @DiFronzo , @jhsoby : Is there some reason why we could not just update the row in cases of collision? Ie. like this? It seems pretty easy and elegant solution, currently i am not able to wrap my mind so that i could see if there is some unwanted side effects.

https://github.com/WikimediaNorge/UKBot/blob/main/ukbot/user.py#L342
```
        # Insert all revisions
        chunk_size = 1000
        for n in range(0, len(contribs_query_params), chunk_size):
            data = contribs_query_params[n:n+chunk_size]
            # logger.info('Adding %d contributions to database', len(data))

            t0 = time.time()
            cur.executemany("""
                insert into contribs (revid, site, parentid, user, page, timestamp, size, parentsize, parsedcomment, ns)
                values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                on duplicate key update
                    parentid=values(parentid),
                    user=values(user),
                    page=values(page),
                    timestamp=values(timestamp),
                    size=values(size),
                    parentsize=values(parentsize),
                    parsedcomment=values(parsedcomment),
                    ns=values(ns)
                """, data
            )
            dt = time.time() - t0
            logger.info('Added %d contributions to database in %.2f secs', len(data), dt)

```

**Comment by DiFronzo** [comment]
@zache-fi: I like the `on duplicate key update` solution. But we also need to be aware of after a rename, the old rows for user A will be "moved" to user B. That is what we want, but it means contribution history in the DB no longer reflects the old username. For UKBot that is fine, since scoring is per current user, but worth knowing. Make a PR on it 🤘 Great work!
